title: Jennifer F. Arthur
description: Glaciologist and Remote Sensing Scientist
baseurl: ""
url: "https://jennyfarthur.github.io"

theme: minimal-mistakes-jekyll

author:
  name: Jennifer F. Arthur

# Navigation menu
nav:
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Outreach
    url: /outreach/
  - title: CV
    url: /cv/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
