title: Jenny F. Arthur
description: Researcher in Glaciology
baseurl: ""       # leave empty for GitHub Pages
url: "https://jennyfarthur.github.io"

# Use the remote Minimal Mistakes theme
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

