title: Jenny F. Arthur
description: Researcher in Glaciology and Earth Observation
baseurl: "" # leave empty for GitHub Pages
url: "https://jennyfarthur.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: GitHub
    url: https://github.com/jennyfarthur
