title: Jenny F. Arthur
description: Researcher in Glaciology and Earth Observation
baseurl: "" # leave empty for GitHub Pages
url: "https://jennyfarthur.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
